ConsommiTounsi/Controllers/LivreurController.cs
using ConsommiTounsi.Models;
using IronRuby.Runtime;
using Solution.Domain.Entities;
using Solution.Service;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ConsommiTounsi.Controllers
{
    public class LivreurController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        ILivreurService Service;
        public LivreurController()
        {
            Service = new LivreurService();
        }
        // GET: Livreur
        public ActionResult Index()
        {
            return View(Service.GetMany());
        }

        // GET: Livreur/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Livreur/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Livreur/Create
        [HttpPost]
        public ActionResult Create(Livreur livreur)
        {
            
            Service.Add(livreur);
            Service.Commit();
            return RedirectToAction("Index");
        }

        // GET: Livreur/Edit/5
        
        public ActionResult Edit(int id)
        {
            return View(Service.GetById(id));
        }

        // GET: Livreur/Stat/5
        public ActionResult Stat(int id)
        {
            return View(Service.GetById(id));
        }

        [HttpPost]
        public JsonResult NewChart()
        {
            List<object> iData = new List<object>();
            //Creating sample data  
            DataTable dt = new DataTable();
            dt.Columns.Add("Date", System.Type.GetType("System.DateTime"));
            dt.Columns.Add("Livraison", System.Type.GetType("System.Int32"));

            DataRow dr = dt.NewRow();
            dr["Date"] = "2020-03-23";
            dr["Livraison"] = 30;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["Date"] = "2020-03-24";
            dr["Livraison"] = 35;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["Date"] = "2020-03-25";
            dr["Livraison"] = 25;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["Date"] = "2020-03-26";
            dr["Livraison"] = 20;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["Date"] = "2020-03-27";
            dr["Livraison"] = 40;
            dt.Rows.Add(dr);
            dr = dt.NewRow();

            dr["Date"] = "2020-03-28";
            dr["Livraison"] = 10;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["Date"] = "2020-03-29";
            dr["Livraison"] = 0;
            dt.Rows.Add(dr);

            //Looping and extracting each DataColumn to List<Object>  
            foreach (DataColumn dc in dt.Columns)
            {
                List<object> x = new List<object>();
                x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                iData.Add(x);
            }
            //Source data returned as JSON  
            return Json(iData, JsonRequestBehavior.AllowGet);
        }
        // GET: Livreur/Edit1/5

        public ActionResult Edit1(int id)
        {
            return View(Service.GetById(id));
        }

        // POST: Livreur/Edit/5

        // POST: Livreurs/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        public ActionResult Edit(int id,Livreur liv)
        {
            try
            {
                Livreur l = Service.GetById(id);
                l.LastName = liv.LastName;
                l.FirstName = liv.FirstName;
                Service.Update(l);
                Service.Commit();
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // POST: Livreur/Edit1/5

        // POST: Livreurs/Edit1/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit1(int id, Livreur liv)
        {
            try
            {
                Livreur l = Service.GetById(id);
                l.Disponibilité = liv.Disponibilité;
                l.Distance = liv.Distance;
                l.Affectation = liv.Affectation;
                Service.Update(l);
                Service.Commit();
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Livreur/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(Service.GetById(id));
        }

        // POST: Livreur/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Livreur livreur)
        {
            try
            {
                //Service.Delete(client);
                //Service.Commit();
                //Service.Dispose();
                Livreur c = Service.GetById(id);
                Service.Delete(c);
                Service.Commit();

                //Service.Delete(Service.Get(x=>x.ClientId.Equals(c)));
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
    }
}

ConsommiTounsi/Controllers/LivreursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConsommiTounsi.Models;
using Solution.Domain.Entities;

namespace ConsommiTounsi.Controllers
{
    public class LivreursController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Livreurs
        public ActionResult Index()
        {
            return View(db.Livreurs.ToList());
        }

        // GET: Livreurs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livreur livreur = db.Livreurs.Find(id);
            if (livreur == null)
            {
                return HttpNotFound();
            }
            return View(livreur);
        }

        // GET: Livreurs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Livreurs/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Salary,Address,Age")] Livreur livreur)
        {
            if (ModelState.IsValid)
            {
                db.Livreurs.Add(livreur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(livreur);
        }

        // GET: Livreurs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livreur livreur = db.Livreurs.Find(id);
            if (livreur == null)
            {
                return HttpNotFound();
            }
            return View(livreur);
        }

        // POST: Livreurs/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Salary,Address,Age")] Livreur livreur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(livreur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(livreur);
        }

        // GET: Livreurs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livreur livreur = db.Livreurs.Find(id);
            if (livreur == null)
            {
                return HttpNotFound();
            }
            return View(livreur);
        }

        // POST: Livreurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Livreur livreur = db.Livreurs.Find(id);
            db.Livreurs.Remove(livreur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConsommiTounsi/Views/Livreur/Create.cshtml
@model Solution.Domain.Entities.Livreur

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/CreateLivreur.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    
}

ConsommiTounsi/Views/Livreur/Delete.cshtml
@model Solution.Domain.Entities.Livreur

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/DeleteLivreur.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


}

ConsommiTounsi/Views/Livreur/Edit.cshtml
@model Solution.Domain.Entities.Livreur

@{
    ViewBag.Title = "Edit";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Livreurs</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item ">List Livreurs</li>
                    <li class="breadcrumb-item active">Modifier Livreurs</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main row -->
<div class="row">
    <!-- Left col -->
    <section class="col-lg-7 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->

        <div class="card-header">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-info" />
                        </div>
                    </div>
                </div>

            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

        </div>
    </section>
    <!-- /.Left col -->


</div>
<!-- /.row (main row) -->

ConsommiTounsi/Views/Livreur/Index.cshtml
@model IEnumerable<Solution.Domain.Entities.Livreur>


@{
    ViewBag.Title = "Livreurs";
}


<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Livreurs</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">List Livreurs</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"></h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.FirstName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.LastName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Salary)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Address)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Age)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Disponibilité)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Distance)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Affectation)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Salary)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Age)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Disponibilité)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Distance)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Affectation)
                                </td>
                                <td>
                                    <button onclick="location.href='@Url.Action("Edit", "Livreur", new { id = item.Id })';return false;" class="btn btn-primary">Edit</button>
                                    <button onclick="location.href='@Url.Action("Delete", "Livreur", new { id = item.Id })';return false;" class="btn btn-danger">Delete</button>
                                    <button onclick="location.href='@Url.Action("Stat", "Livreur", new { id = item.Id })';return false;" class="btn btn-success">Stat</button>
                                    <button onclick="location.href='@Url.Action("Edit1", "Livreur", new { id = item.Id })';return false;" class="btn btn-primary">Affecter</button>
                                </td>
                            </tr>
                            }
                        </tbody>
                        
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <button onclick="location.href='@Url.Action("Create", "Livreur")';return false;" class="btn btn-primary float-right">Create New</button>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

ConsommiTounsi/Views/Livreur/Stat.cshtml
@model Solution.Domain.Entities.Livreur

@{
    ViewBag.Title = "Stat";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Livreurs : @Html.DisplayFor(model => model.FirstName)-@Html.DisplayFor(model => model.LastName)</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item "><a href="/Livreur">List Livreurs</a></li>
                        <li class="breadcrumb-item active">Stat Livreur</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>150</h3>

                            <p>New Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>53<sup style="font-size: 20px">%</sup></h3>

                            <p>Bounce Rate</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>44</h3>

                            <p>User Registrations</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>65</h3>

                            <p>Unique Visitors</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
            <div class="row">
                <!-- /.row -->
                <section class="col-lg-12 connectedSortable">
                    <!-- Custom tabs (Charts with tabs)-->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-chart-pie mr-1"></i>
                                Livraisons
                            </h3>
                            <div class="card-tools">
                                <ul class="nav nav-pills ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#revenue-chart" data-toggle="tab">Bar</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#sales-chart" data-toggle="tab">Line</a>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-content p-0">
                                <!-- Morris chart - Sales -->
                                <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 100%;">
                                    <div Style="font-family: Corbel; font-size: small ;text-align:center " class="row">
                                        <div style="width:100%;height:100%">
                                            <canvas id="myChartbar" style="padding: 0;margin: auto;display: block; "> </canvas>
                                        </div>
                                    </div>
                                </div>
                                <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 100%;">
                                    <div Style="font-family: Corbel; font-size: small ;text-align:center " class="row">
                                        <div style="width:100%;height:100%">
                                            <canvas id="speedChart" style="padding: 0;margin: auto;display: block; "></canvas>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </section>

            </div>
    </section>
}

@section head
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
}

<script>

    $.ajax({
        type: "POST",
        url: '@Url.Action("NewChart", "Livreur")',
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (chData) {
            var aData = chData;
            var aLabels = aData[0];
            var aDatasets1 = aData[1];
            var dataT = {
                labels: aLabels,
                datasets: [{
                    label: '@Html.DisplayFor(model => model.FirstName)-@Html.DisplayFor(model => model.LastName) ',
                    data: aDatasets1,
                    fill: false,
                    backgroundColor: ["rgba(54, 162, 235, 0.2)", "rgba(255, 99, 132, 0.2)", "rgba(255, 159, 64, 0.2)", "rgba(255, 205, 86, 0.2)", "rgba(75, 192, 192, 0.2)", "rgba(153, 102, 255, 0.2)", "rgba(201, 203, 207, 0.2)"],
                    borderColor: ["rgb(54, 162, 235)", "rgb(255, 99, 132)", "rgb(255, 159, 64)", "rgb(255, 205, 86)", "rgb(75, 192, 192)", "rgb(153, 102, 255)", "rgb(201, 203, 207)"],
                    borderWidth: 1
                }]
            };
            var chartOptions = {
              legend: {
                display: true,
                position: 'top',
                labels: {
                  boxWidth: 80,
                  fontColor: 'black'
                }
              },
              scales: {
                  xAxes: [{
                      type: "time",
                       time: {
                            unit: 'day',
                            round: 'day',
                            tooltipFormat: "D MM YYYY"
                          },
                      gridLines: {
                        display: false,
                        color: "black"
                      },
                      scaleLabel: {
                        display: true,
                        labelString: "Dates",
                        fontColor: "red"
                      }
                  }],
                yAxes: [{
                  gridLines: {
                    color: "black",
                    borderDash: [2, 5],
                  },
                  scaleLabel: {
                    display: true,
                    labelString: "Livraison",
                    fontColor: "green"
                  }
                }]
              }
            };
            var ctx = $("#myChartbar").get(0).getContext("2d");
            var speedCanvas = document.getElementById("speedChart");
            var myNewChart = new Chart(ctx, {
                type: 'bar',
                data: dataT,
                options:chartOptions
                }
            );
            
            //Chart.defaults.global.defaultFontFamily = "Lato";
            //Chart.defaults.global.defaultFontSize = 18;
            

            var lineChart = new Chart(speedCanvas, {
              type: 'line',
              data: dataT,
              options: chartOptions
            });
        }
    });
</script>